### PR TITLE
made game version of a card entity, with modifiable hp

### PR DESCRIPTION
**Pull request by ThomasKeough**
new card entity and interface. GamePokemon is the interface. GameCard is the implementation. methods that will be used in game loop have been added. more methods may be required later.

### CODE REVIEW

**Comment by dharhar** [comment]
I think if we have a takeDamage method here we should also incorporate the Type of the pokemon (resistances + weaknesses) too whenever we change the Pokemon's hp. That way it will be more consistent, and we won't need to have a method to look at the resistance / weakness values in the attack use case

**Review by dharhar — CHANGES_REQUESTED** [review]
I think if we have a takeDamage method here we should also incorporate the Type of the pokemon (resistances + weaknesses) too whenever we change the Pokemon's hp. That way it will be more consistent, and we won't need to have a method to look at the resistance / weakness values in the attack use case

**Review by stanleypangg — APPROVED** [review]
Good stuff! I agree with Dharma's comment though, but as for the fundamentals everything looks nice. Incorporating the type would be good for consistency and encapsulation. It'll reduce the need to inspect resistance/weakness values during the attack use case. Also, I believe the UseCaseInteractor delegates all the work to the entities with their methods, so I think that'd align more with Clean Archiecture. Anyways let me know what you think.

**Comment by ThomasKeough** [comment]
> I think if we have a takeDamage method here we should also incorporate the Type of the pokemon (resistances + weaknesses) too whenever we change the Pokemon's hp. That way it will be more consistent, and we won't need to have a method to look at the resistance / weakness values in the attack use case

actually i think it would make more sense to have the type multipliers be handled by the attack use case. that way we can keep the GameCard entity as simple as possible. otherwise, the attack use case would just be calling takeDamage(), and wouldn't be much of a use case at all. i think this would satisfy SOLID principles better

**Review by dharhar — APPROVED** [review]
ok sounds good i'll handle the multipliers in the attack use case

**Pull request merged**
