### PR TITLE
Josh build card

### PR DESCRIPTION
**Pull request by jvenchy**
Most of this branch is work towards the TCG DAO, which calls the API to pull all 151 pokémon from the set ScarletViolet151 to store in a csv, so that we can have a circulation of cards and their data, either to be added into user's use_cases.collection or used by bot. Made so the current set in circulation can be switched out anytime. 

Tested, works and creates a CSV file of format (id, name, type, isHighHP, isEXorMega) per line. Ex: sv3pt5-2,Ivysaur,Grass,false,false. 

CSV is meant to be accessed by Collection, which takes ids and calls CommonCardFactory to create Card objects later on.

### CODE REVIEW

**Comment by ThomasKeough** [comment]
@dharhar pls take a look when u get a chance. want u to see how the code u initially wrote is being changed before merging, so that we're all on the same page

**Review by dharhar — CHANGES_REQUESTED** [review]
Everything is looking good so far, I'm just curious what "sv3pt5" means in the TradingCardGameDAO file (add a comment pls). 

The writeDataToCSV method in the file writes more than just the id and name of a pokemon to the file (it writes the type, isHighHp, and isSpecial too). This isn't consistent with CardDAO's save() method. I think you should update either one of the methods to make sure that all the other attributes are written to the file. 

Also in the writeDataToCSV method, you have ... + "," + isHighHp + ... 
I think you need to use Boolean.parseBoolean(String str) here to convert from boolean to string (this applies for isHighHp and isSpecial).

Last thing is to just maybe add a // TODO: in CollectionDataAccessInterface just so we remember to implement that next time.

**Comment by jvenchy** [comment]
thanks for catching that, dharma. Will make changes when I get the chance and request again 💯

**Comment by ThomasKeough** [comment]
noticed a merge conflict here after merging stanley's builddeck code, it has been resolved

**Review by dharhar — CHANGES_REQUESTED** [review]
- [ ] Fix code in CommonCardFactory to clean up data (damage values in the JSON are formatted differently - some have 3 digits, some have 2 digits and a symbol, some are empty strings, and some are strings of 2 digits)

**Review by dharhar — APPROVED** [review]
looks good, i think we can merge this

**Review by dharhar — CHANGES_REQUESTED** [review]
nvm i didn't realise that you haven't handled the empty string case in CommonCardFactory (if the damage value is an empty string, Integer.parseInt() will throw an exception)

**Review by dharhar — APPROVED** [review]
looks good for real now 💯

**Pull request merged**
